### ISSUE TITLE
The version number is missing in release

### ISSUE THREAD

**Issue by cdwmhcc** [nuance-dev/Figura#1]
Thanks to the developer for the utility.
I found that the items in releases are missing version numbers. Is it possible to follow https://semver.org/

**Comment by nuance-dev** [comment]
Updated code and release to use semver versioning, thanks!

**Comment by cdwmhcc** [comment]
> Updated code and release to use semver versioning, thanks!

Thank you so much for the hard work and quick responses from the developers! This is awesome. It not only helps users better understand the contents of each update but also enhances the professionalism of the project. I am looking forward to more updates and improvements in the future! 👍

Don't forget Medio 😄

**Comment by nuance-dev** [comment]
No no, thank you for helping me improve the apps! I already updated all of them to use this versioning ✌️
